# Generated by Django 2.2.7 on 2019-11-27 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog_Post',
            new_name='BlogPost',
        ),
    ]
