# Generated by Django 2.2.7 on 2019-11-27 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191127_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 27, 13, 56, 17, 268801), verbose_name='published on'),
        ),
    ]
