# Generated by Django 2.2.7 on 2019-11-27 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191127_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 27, 14, 6, 41, 390003), verbose_name='published on'),
        ),
    ]
