# Generated by Django 2.2.7 on 2019-11-27 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191127_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 27, 19, 58, 25, 689429), verbose_name='published on'),
        ),
    ]
